version: "3"

services: 
    flutter:
        image: flutter:x11
        privileged: true
        command: /opt/android-sdk-linux/emulator/emulator -use-system-libs @teste -no-boot-anim -no-audio -no-window -writable-system -memory 2048