version: "3"

services: 
    flutter:
        image: flutter:x11
        privileged: true
        volumes:
            - ./entrypoint.sh:/usr/bin/entrypoint.sh
        entrypoint: /usr/bin/entrypoint.sh
        ports:
            - 5900:5900